FROM node:18 as builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npm run build

FROM node:18 

COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD [ "npm", "run", "start:dev" ]

